PROGRAM MAIN
USE PRECISION
USE PROBLEM_DEF
IMPLICIT NONE

 CALL OPENMP_SETTING
 
 CALL SETUP

 DO
 	
  ITER = ITER + 1
  TIME = TIME + DT
  
  CALL SOLVE_VOF
  CALL SOLVE_LS
  CALL SOLVE_NS
  CALL FIND_MASS
  CALL PRINT_SCREEN
  CALL PLOT
  
  IF( TIME>TIME_TO_STOP )EXIT
  
  CALL STORE_DATA  
  CALL CPU_REC
  
 END DO

 CALL TO_FILE2()
 CALL FREE_ARRAY()

CONTAINS

INCLUDE "OPENMP_SETTINGS.F90"
INCLUDE "STORE_DATA.F90"
INCLUDE "SOLVE_PRESSURE_POISSON.F90"
INCLUDE "SOLVE_NS.F90"
INCLUDE "SETUP.F90"
INCLUDE "ALLOCATE_ARRAY.F90"
INCLUDE "PLOT.F90"
INCLUDE "LS_REDISTANCE.F90"
INCLUDE "SCHEME_WENO.F90"
INCLUDE "SCHEME_COMPACT.F90"
INCLUDE "FIND_ERROR.F90"
INCLUDE "BC.F90"
INCLUDE "FIND_CURVATURE.F90"
INCLUDE "AMURHO.F90"
INCLUDE "LS_SOLVER.F90"
INCLUDE "VORTEX_VELOCITY.F90"
INCLUDE "FIND_MASS.F90"
INCLUDE "PRINT_SCREEN.F90"
INCLUDE "TDMA.F90"
INCLUDE "LS_MAINTAIN.F90"
INCLUDE "VOF_SOLVER.F90"
INCLUDE "TO_FILE.F90"
INCLUDE "READ_DATA.F90"
INCLUDE "ERROR_ESTIMATION.F90"
INCLUDE "FIND_NORMALS.F90"
INCLUDE "VORTEX_IDENTIFICATION.F90"
INCLUDE "CPU_REC.F90"
INCLUDE "SECOND_ORDER_UPWIND.F90"
INCLUDE "QUICK.F90"

END PROGRAM MAIN
