SUBROUTINE PLOT()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES, ONLY : U,V,W,P,RHO,AMU
USE LS_DATA, ONLY : PHI, HEAVY, CURV, phi1, phi2
USE VOF_DATA, ONLY : VOF
USE DUMMY_DATA, ONLY : F,G
USE IBM_DATA
IMPLICIT NONE
INTEGER :: I,J,K
REAL(DP) :: cpu_PLOT
CHARACTER(3) :: MET,GRI,NUM

  IF(ABS(ITER*DT-PLOT_INT*TIME_TO_PLOT)<DT)THEN
    CONTINUE
  ELSE
    RETURN
  END IF
  
  cpu_PLOT = -wtime ( )
  
  CALL HEAVY_F(PHI)
  !CALL VORTEX_IDENTIFICATION()

  WRITE(MET,'(I3.3)')METHOD_CNT
  WRITE(GRI,'(I3.3)')GRID_CNT
  WRITE(NUM,'(I3.3)')PLOT_INT
  !OPEN(UNIT=99,FILE='Nesq_3D_'//Met//'_'//GRI//'_'//NUM//'_.dat',STATUS="UNKNOWN")
  !OPEN(UNIT=99,FILE='Dam_3D_'//met//'_'//num//'.dat',STATUS="UNKNOWN")
  OPEN(UNIT=99,FILE='MC_3D_'//num//'.dat',STATUS="UNKNOWN")
  WRITE(99,*) 'TITLE = "T='//NUM//'" '
  
SELECT CASE(IBM_SOLVER)
 CASE(0)
    !WRITE(99,*) 'VARIABLES =  "X" "Y" "Z" "u" "v" "w" "p" "phi" "curvature" "Q-cri" "delta-cri" '
    WRITE(99,*) 'VARIABLES =  "X" "Y" "Z" "phi" "phi1" "phi2"'
 CASE(1)
    WRITE(99,*) 'VARIABLES =  "X" "Y" "Z" "u" "v" "w" "phi" "vof" "SOLID"'
END SELECT

100 FORMAT('ZONE T= "NUMERICAL" , I=', I4,', J=', I4, ', K=', I4,', F= POINT' )

WRITE(99,100) NODE_X+2,NODE_Y+2,NODE_Z+2

SELECT CASE(IBM_SOLVER)
 CASE(0) 
  DO K = 0, NODE_Z+1
  DO J = 0, NODE_Y+1
  DO I = 0, NODE_X+1
    !WRITE(99,'(15E14.4)')X(I),Y(J),Z(K),U(I,J,K),V(I,J,K),W(I,J,K),P(I,J,K),PHI(I,J,K),CURV(I,J,K),F(I,J,K),G(I,J,K)
    WRITE(99,'(15E14.4)')X(i),Y(J),Z(k),phi(I,J,K), phi1(i,j,k), phi2(i,j,k)
  END DO
  END DO
  END DO
 CASE(1)
   DO K = 0, NODE_Z+1
   DO J = 0, NODE_Y+1
   DO I = 0, NODE_X+1
      WRITE(99,'(9E11.4)')X(I),Y(J),Z(K),U(I,J,K),V(I,J,K),W(I,J,K),HEAVY(I,J,K),VOF(I,J,K),SOLID_VOF(I,J,K)
   END DO
   END DO
   END DO
END SELECT
 CLOSE(UNIT=99)

PLOT_INT=PLOT_INT+1

 cpu_PLOT = cpu_PLOT + wtime ( )

 CPU_COST = CPU_COST - cpu_PLOT

END SUBROUTINE
