SUBROUTINE STORE_DATA()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
IMPLICIT NONE
INTEGER :: I,J,K

 !$OMP PARALLEL DO
 DO K = -2, NODE_Z+3
 DO J = -2, NODE_Y+3
 DO I = -2, NODE_X+3
 
   PHI_OLD(I,J,K) = PHI(I,J,K)
   VOF_OLD(I,J,K) = VOF(I,J,K)
   
   U_OLD(I,J,K) = U(I,J,K)
   V_OLD(I,J,K) = V(I,J,K)
   W_OLD(I,J,K) = W(I,J,K)
   
   US_OLD(I,J,K) = US(I,J,K)
   VS_OLD(I,J,K) = VS(I,J,K)
   WS_OLD(I,J,K) = WS(I,J,K)
   
   RHO_OLD(I,J,K) = RHO(I,J,K)
   AMU_OLD(I,J,K) = AMU(I,J,K)
 
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO

END SUBROUTINE